
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
    version: blue  # Change this to 'green' to switch traffic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
